### PR TITLE
EZS-1160: Content on the fly shows undefined when content type description is empty

### PR DESCRIPTION
**Pull request by dew326**
**Jira ticket:** https://jira.ez.no/browse/EZS-1160

### CODE REVIEW

**Comment by dew326** [comment]
ping @lserwatka @micszo

**Review by micszo — APPROVED** [review]
👍 retest OK.

**Comment by andrerom** [comment]
ok, but shouldn't the popup be hidden if there is no text? or is that the case with this?

**Comment by dew326** [comment]
yes, the tooltip is hidden if the description is not set.

**Pull request merged**
