### PR TITLE
EZS-828: Duplicated entry in assetic configuration leads to css 404…

### PR DESCRIPTION
**Pull request by dew326**
…problems on linux machines

**Jira ticket:** https://jira.ez.no/browse/EZS-828

### CODE REVIEW

**Comment by dew326** [comment]
ping @lserwatka @sunpietro @Nattfarinn

**Comment by lserwatka** [comment]
+1

**Comment by Nattfarinn** [comment]
+1

**Comment by sunpietro** [comment]
+1

**Pull request merged**
