### PR TITLE
EZP-28161: Update php-cs-fixer configuration to align with v2.7.1

### PR DESCRIPTION
**Pull request by alongosz**
# Fixes [EZP-28161](https://jira.ez.no/browse/EZP-28161)

This PR updates `.php_cs` config and aligns CS.
To simplify fixing code it adds dependency on `php-cs-fixer` and introduces composer command:
```
composer fix-cs
```
which runs fixer on all files.

**TODO**:
- [x] Update php-cs-fixer config (`.php_cs`)
- [x] Update CS
- [x] Add `php-cs-fixer` dev dependency to composer pointing to `~2.7.1`
- [x] Add composer command `fix-cs`
- [x] Add missing `.gitignore` file // out of scope, but kind of related

### CODE REVIEW

**Review by andrerom — APPROVED** [review]

**Comment by alongosz** [comment]
@micszo is behat failure a normal thing here also? :)

**Comment by micszo** [comment]
@mnocon could this be related to the issues we see in StudioUIBundle?

**Comment by mnocon** [comment]
@micszo the first failure is probably caused by this: https://jira.ez.no/browse/EZEE-1737 (I've made changes so that the test passes in my refactor PR)
The second failure is most likely caused by the thing I'm investigating.

**Comment by alongosz** [comment]
So this isn't caused by any dependency issues due to composer.json changes? If we run tests on Symfony `<3.2` it happens for this change. In other words: is this one OK despite CI error? :)

**Review by micszo — APPROVED** [review]
@alongosz I would say yes, 99% OK.

**Pull request merged**
