### PR TITLE
EZS-1289: Application stops on spinner when trying to edit new scheduled draft

### PR DESCRIPTION
**Pull request by sunpietro**
https://jira.ez.no/browse/EZS-1289

### CODE REVIEW

**Comment by sunpietro** [comment]
ping @micszo @dew326 @lserwatka

**Review by andrerom — APPROVED** [review]

**Review by dew326 — APPROVED** [review]

**Comment by micszo** [comment]
@sunpietro this needs to go to 1.7 :) sorry, did not manage to check that before.

**Comment by sunpietro** [comment]
We don't have 1.7 branch

**Comment by micszo** [comment]
Indeed, it's different in this bundle.

**Review by micszo — APPROVED** [review]
Retest OK.

**Pull request merged**
